-- ============================================================
-- SAANSSYNC DATABASE SCHEMA (FINALIZED)
-- Includes: All Tables, Authentication, Security, and Indexes
-- ============================================================

-- 0. CLEANUP & EXTENSIONS
-- =========================
GRANT USAGE ON SCHEMA public TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO service_role;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. CORE AUTH & PROFILES
-- =========================

-- Doctors Table
-- Stores profile linked to Supabase Auth (admin approved)
CREATE TABLE IF NOT EXISTS public.doctors (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  auth_user_id UUID REFERENCES auth.users(id), -- Linked only upon approval
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT UNIQUE,
  alt_phone TEXT,
  approval_status TEXT NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Patients Table
-- Created by doctors, then linked to Auth for login
CREATE TABLE IF NOT EXISTS public.patients (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  auth_user_id UUID REFERENCES auth.users(id), -- Linked upon first login/OTP verification
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT UNIQUE,
  doctor_id UUID REFERENCES public.doctors(id), -- Primary doctor
  disease_type TEXT NOT NULL, -- "Asthma", "COPD", etc.
  patient_data JSONB DEFAULT '{}', -- Flexible profile (meds, diagnosis, baseline)
  default_password TEXT, -- Temporary password for first login
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. DOMAIN LOGIC
-- =========================

-- Patient Folders (Materialized View style)
-- Stores the latest "State" of a patient for the Doctor Dashboard
CREATE TABLE IF NOT EXISTS public.patient_folders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id UUID NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  age INTEGER DEFAULT 0,
  disease_type TEXT NOT NULL,
  folder_color TEXT NOT NULL DEFAULT 'green' CHECK (folder_color IN ('green', 'yellow', 'orange', 'red')),
  red_flag_score NUMERIC DEFAULT 1,
  alert_count INTEGER DEFAULT 0,
  last_log_date TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(doctor_id, patient_id) -- One folder per doctor-patient pair
);

-- Daily Logs (The "Source of Truth" for scoring)
-- Stores the full daily submission + computed score
CREATE TABLE IF NOT EXISTS public.daily_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  log_date DATE NOT NULL,
  disease_type TEXT NOT NULL,
  disease_data JSONB NOT NULL, -- Stores common + specific log data + drivers
  red_flag_score NUMERIC DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(patient_id, log_date) -- Prevent duplicate logs per day
);

-- Alerts (Historical & Active)
-- Generated by scoring engine when risk > Green or Critical Trigger
CREATE TABLE IF NOT EXISTS public.saanssync_alerts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id UUID REFERENCES public.doctors(id),
  level TEXT NOT NULL CHECK (level IN ('GREEN', 'YELLOW', 'ORANGE', 'RED')),
  score NUMERIC NOT NULL,
  reason_text TEXT NOT NULL, -- Human readable summary
  alert_data JSONB DEFAULT '{}', -- Structured drivers
  disease_type TEXT NOT NULL,
  acknowledged BOOLEAN DEFAULT FALSE,
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Prescriptions
-- Stores med history (used in dashboard tabs)
CREATE TABLE IF NOT EXISTS public.prescriptions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id UUID REFERENCES public.doctors(id),
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  medications JSONB NOT NULL DEFAULT '[]', -- Array of { drugName, dose, freq }
  instructions TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PFT Records
-- Stores Pulmonary Function Tests
CREATE TABLE IF NOT EXISTS public.pft_records (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  values JSONB NOT NULL DEFAULT '{}', -- FEV1, FVC, Ratio
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Doctor Instructions / Notes
-- Stores persistent notes for patient dashboard
CREATE TABLE IF NOT EXISTS public.doctor_instructions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id UUID REFERENCES public.doctors(id),
  instruction TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Doctor-Patient Assignments (Many-to-Many fallback)
-- Primarily used if a patient is shared, but usually doctor_id in patients table is source of truth.
CREATE TABLE IF NOT EXISTS public.doctor_patient_assignments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  doctor_id UUID NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE,
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(doctor_id, patient_id)
);

-- Doctor-Patient Mapping (For legacy legacy/redundancy if referenced in API)
CREATE TABLE IF NOT EXISTS public.doctor_patient_mapping (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    doctor_id UUID NOT NULL REFERENCES public.doctors(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    disease_type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(doctor_id, patient_id)
);

-- 3. INDEXES
-- =========================
CREATE INDEX idx_logs_patient_date ON public.daily_logs(patient_id, log_date DESC);
CREATE INDEX idx_alerts_doctor_unread ON public.saanssync_alerts(doctor_id, acknowledged) WHERE acknowledged = FALSE;
CREATE INDEX idx_folders_doctor ON public.patient_folders(doctor_id);
CREATE INDEX idx_patients_phone ON public.patients(phone);

-- 4. RLS POLICIES (Backend Service Role Pattern)
-- =========================
-- Since the application uses "Service Role" mostly for backend operations,
-- we enforce strict RLS to prevent accidental public access.

ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saanssync_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_folders ENABLE ROW LEVEL SECURITY;

-- Policy: Service Role has full access (Implicit in Supabase but good to document)
-- Policy: Anon should typically have NO access (Everything via API)

-- 5. PERMISSIONS
-- =========================
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
